<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StopSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $locations_lu = array(
            array("id" => 1, "stop_org" => "Abweiler", "stop" => "Abweiler"),
            array("id" => 2, "stop_org" => "Aessen", "stop" => "Aessen"),
            array("id" => 3, "stop_org" => "Ahn", "stop" => "Ahn"),
            array("id" => 4, "stop_org" => "Akescht", "stop" => "Akescht"),
            array("id" => 5, "stop_org" => "Alf", "stop" => "Alf"),
            array("id" => 6, "stop_org" => "Allerborn", "stop" => "Allerborn"),
            array("id" => 7, "stop_org" => "Almillen", "stop" => "Almillen"),
            array("id" => 8, "stop_org" => "Alrodeschhaff", "stop" => "Alrodeschhaff"),
            array("id" => 9, "stop_org" => "Alscheid", "stop" => "Alscheid"),
            array("id" => 10, "stop_org" => "Altlinster", "stop" => "Altlinster"),
            array("id" => 11, "stop_org" => "Altrier", "stop" => "Altrier"),
            array("id" => 12, "stop_org" => "Altwies", "stop" => "Altwies"),
            array("id" => 13, "stop_org" => "Alzingen", "stop" => "Alzingen"),
            array("id" => 14, "stop_org" => "Angelsberg", "stop" => "Angelsberg"),
            array("id" => 15, "stop_org" => "Ansembourg", "stop" => "Ansembourg"),
            array("id" => 16, "stop_org" => "Antoniushaff", "stop" => "Antoniushaff"),
            array("id" => 17, "stop_org" => "Arsdorf", "stop" => "Arsdorf"),
            array("id" => 18, "stop_org" => "Arsdorf-Moulin", "stop" => "Arsdorf-Moulin"),
            array("id" => 19, "stop_org" => "Arsdorferhaff (Sanem)", "stop" => "Arsdorferhaff (Sanem)"),
            array("id" => 20, "stop_org" => "Aspelt", "stop" => "Aspelt"),
            array("id" => 21, "stop_org" => "Assel", "stop" => "Assel"),
            array("id" => 22, "stop_org" => "Asselborn", "stop" => "Asselborn"),
            array("id" => 23, "stop_org" => "Asselborn-Moulin", "stop" => "Asselborn-Moulin"),
            array("id" => 24, "stop_org" => "Asselbur (Kehmen)", "stop" => "Asselbur (Kehmen)"),
            array("id" => 25, "stop_org" => "Asselscheuer", "stop" => "Asselscheuer"),
            array("id" => 26, "stop_org" => "Aéroport de Luxembourg", "stop" => "Aéroport de Luxembourg"),
            array("id" => 27, "stop_org" => "BOUS", "stop" => "BOUS"),
            array("id" => 28, "stop_org" => "Bache-Jang", "stop" => "Bache-Jang"),
            array("id" => 29, "stop_org" => "Bakesmillen", "stop" => "Bakesmillen"),
            array("id" => 30, "stop_org" => "Bamertal", "stop" => "Bamertal"),
            array("id" => 31, "stop_org" => "Bamhaff", "stop" => "Bamhaff"),
            array("id" => 32, "stop_org" => "Banzelt", "stop" => "Banzelt"),
            array("id" => 33, "stop_org" => "Basbellain", "stop" => "Basbellain"),
            array("id" => 34, "stop_org" => "Bascharage", "stop" => "Bascharage"),
            array("id" => 35, "stop_org" => "Baschleiden", "stop" => "Baschleiden"),
            array("id" => 36, "stop_org" => "Bastendorf", "stop" => "Bastendorf"),
            array("id" => 37, "stop_org" => "Bavigne", "stop" => "Bavigne"),
            array("id" => 38, "stop_org" => "Beaufort", "stop" => "Beaufort"),
            array("id" => 39, "stop_org" => "Beaufort (Ferme de-)(Bertrange)", "stop" => "Beaufort (Ferme de-)(Bertrange)"),
            array("id" => 40, "stop_org" => "Beaufort - Château", "stop" => "Beaufort - Château"),
            array("id" => 41, "stop_org" => "Bech", "stop" => "Bech"),
            array("id" => 42, "stop_org" => "Bech-Kleinmacher", "stop" => "Bech-Kleinmacher"),
            array("id" => 43, "stop_org" => "Bech-Moulin", "stop" => "Bech-Moulin"),
            array("id" => 44, "stop_org" => "Beckerich", "stop" => "Beckerich"),
            array("id" => 45, "stop_org" => "Beeforterheed", "stop" => "Beeforterheed"),
            array("id" => 46, "stop_org" => "Beggen (Luxembourg)", "stop" => "Beggen (Luxembourg)"),
            array("id" => 47, "stop_org" => "Beidweiler", "stop" => "Beidweiler"),
            array("id" => 48, "stop_org" => "Beiler", "stop" => "Beiler"),
            array("id" => 49, "stop_org" => "Belair (Luxembourg)", "stop" => "Belair (Luxembourg)"),
            array("id" => 50, "stop_org" => "Belenhaff", "stop" => "Belenhaff"),
            array("id" => 51, "stop_org" => "Belvaux", "stop" => "Belvaux"),
            array("id" => 52, "stop_org" => "Berbourg", "stop" => "Berbourg"),
            array("id" => 53, "stop_org" => "Berbourg (Ferme de)", "stop" => "Berbourg (Ferme de)"),
            array("id" => 54, "stop_org" => "Berchem", "stop" => "Berchem"),
            array("id" => 55, "stop_org" => "Berdorf", "stop" => "Berdorf"),
            array("id" => 56, "stop_org" => "Bereldange", "stop" => "Bereldange"),
            array("id" => 57, "stop_org" => "Berenthal", "stop" => "Berenthal"),
            array("id" => 58, "stop_org" => "Berg", "stop" => "Berg"),
            array("id" => 59, "stop_org" => "Berg (Colmar-Berg)", "stop" => "Berg (Colmar-Berg)"),
            array("id" => 60, "stop_org" => "Bergem", "stop" => "Bergem"),
            array("id" => 61, "stop_org" => "Berghaff", "stop" => "Berghaff"),
            array("id" => 62, "stop_org" => "Beringen", "stop" => "Beringen"),
            array("id" => 63, "stop_org" => "Beringerberg", "stop" => "Beringerberg"),
            array("id" => 64, "stop_org" => "Berlé", "stop" => "Berlé"),
            array("id" => 65, "stop_org" => "Berschbach", "stop" => "Berschbach"),
            array("id" => 66, "stop_org" => "Bertrange", "stop" => "Bertrange"),
            array("id" => 67, "stop_org" => "Bettange-sur-Mess", "stop" => "Bettange-sur-Mess"),
            array("id" => 68, "stop_org" => "Bettborn", "stop" => "Bettborn"),
            array("id" => 69, "stop_org" => "Bettel", "stop" => "Bettel"),
            array("id" => 70, "stop_org" => "Bettembourg", "stop" => "Bettembourg"),
            array("id" => 71, "stop_org" => "Bettendorf", "stop" => "Bettendorf"),
            array("id" => 72, "stop_org" => "Betzdorf", "stop" => "Betzdorf"),
            array("id" => 73, "stop_org" => "Betzemillen", "stop" => "Betzemillen"),
            array("id" => 74, "stop_org" => "Beyren", "stop" => "Beyren"),
            array("id" => 75, "stop_org" => "Biergerkräiz", "stop" => "Biergerkräiz"),
            array("id" => 76, "stop_org" => "Bigelbach", "stop" => "Bigelbach"),
            array("id" => 77, "stop_org" => "Bigonville", "stop" => "Bigonville"),
            array("id" => 78, "stop_org" => "Bigonville-Moulin", "stop" => "Bigonville-Moulin"),
            array("id" => 79, "stop_org" => "Bigonville-Poteau", "stop" => "Bigonville-Poteau"),
            array("id" => 80, "stop_org" => "Bildgeshaff", "stop" => "Bildgeshaff"),
            array("id" => 81, "stop_org" => "Bill", "stop" => "Bill"),
            array("id" => 82, "stop_org" => "Bilsdorf", "stop" => "Bilsdorf"),
            array("id" => 83, "stop_org" => "Binsfeld", "stop" => "Binsfeld"),
            array("id" => 84, "stop_org" => "Binzrath", "stop" => "Binzrath"),
            array("id" => 85, "stop_org" => "Birelerhaff", "stop" => "Birelerhaff"),
            array("id" => 86, "stop_org" => "Birkelt", "stop" => "Birkelt"),
            array("id" => 87, "stop_org" => "Birkenhaff", "stop" => "Birkenhaff"),
            array("id" => 88, "stop_org" => "Birtrange", "stop" => "Birtrange"),
            array("id" => 89, "stop_org" => "Bissen", "stop" => "Bissen"),
            array("id" => 90, "stop_org" => "Bissen-Moulin", "stop" => "Bissen-Moulin"),
            array("id" => 91, "stop_org" => "Bivange", "stop" => "Bivange"),
            array("id" => 92, "stop_org" => "Bivels", "stop" => "Bivels"),
            array("id" => 93, "stop_org" => "Biwer", "stop" => "Biwer"),
            array("id" => 94, "stop_org" => "Biwerbach", "stop" => "Biwerbach"),
            array("id" => 95, "stop_org" => "Biwisch", "stop" => "Biwisch"),
            array("id" => 96, "stop_org" => "Blaschette", "stop" => "Blaschette"),
            array("id" => 97, "stop_org" => "Bleesbrück", "stop" => "Bleesbrück"),
            array("id" => 98, "stop_org" => "Bleesmillen", "stop" => "Bleesmillen"),
            array("id" => 99, "stop_org" => "Bloëbierg", "stop" => "Bloëbierg"),
            array("id" => 100, "stop_org" => "Blumenthal", "stop" => "Blumenthal"),
            array("id" => 101, "stop_org" => "Blumenthal (Bech)", "stop" => "Blumenthal (Bech)"),
            array("id" => 102, "stop_org" => "Bockholtz", "stop" => "Bockholtz"),
            array("id" => 103, "stop_org" => "Bockholtz (Goesdorf)", "stop" => "Bockholtz (Goesdorf)"),
            array("id" => 104, "stop_org" => "Bockholtz-Moulin", "stop" => "Bockholtz-Moulin"),
            array("id" => 105, "stop_org" => "Bockmillen", "stop" => "Bockmillen"),
            array("id" => 106, "stop_org" => "Boevange", "stop" => "Boevange"),
            array("id" => 107, "stop_org" => "Boevange-sur-Attert", "stop" => "Boevange-sur-Attert"),
            array("id" => 108, "stop_org" => "Bofferdange", "stop" => "Bofferdange"),
            array("id" => 109, "stop_org" => "Bollendorf-Pont", "stop" => "Bollendorf-Pont"),
            array("id" => 110, "stop_org" => "Bomicht", "stop" => "Bomicht"),
            array("id" => 111, "stop_org" => "Bomillen", "stop" => "Bomillen"),
            array("id" => 112, "stop_org" => "Bommelscheuer", "stop" => "Bommelscheuer"),
            array("id" => 113, "stop_org" => "Bonnal", "stop" => "Bonnal"),
            array("id" => 114, "stop_org" => "Bonnevoie (Luxembourg)", "stop" => "Bonnevoie (Luxembourg)"),
            array("id" => 115, "stop_org" => "Born", "stop" => "Born"),
            array("id" => 116, "stop_org" => "Born-Moulin", "stop" => "Born-Moulin"),
            array("id" => 117, "stop_org" => "Boudler", "stop" => "Boudler"),
            array("id" => 118, "stop_org" => "Boudlerbach", "stop" => "Boudlerbach"),
            array("id" => 119, "stop_org" => "Boulaide", "stop" => "Boulaide"),
            array("id" => 120, "stop_org" => "Boulaide-Moulin", "stop" => "Boulaide-Moulin"),
            array("id" => 121, "stop_org" => "Bour", "stop" => "Bour"),
            array("id" => 122, "stop_org" => "Bourglinster", "stop" => "Bourglinster"),
            array("id" => 123, "stop_org" => "Bourglinster - Château", "stop" => "Bourglinster - Château"),
            array("id" => 124, "stop_org" => "Bourscheid", "stop" => "Bourscheid"),
            array("id" => 125, "stop_org" => "Bourscheid - Château", "stop" => "Bourscheid - Château"),
            array("id" => 126, "stop_org" => "Bourscheid Moulin", "stop" => "Bourscheid Moulin"),
            array("id" => 127, "stop_org" => "Bourscheid-Plage", "stop" => "Bourscheid-Plage"),
            array("id" => 128, "stop_org" => "Boursdorf", "stop" => "Boursdorf"),
            array("id" => 129, "stop_org" => "Boxhorn", "stop" => "Boxhorn"),
            array("id" => 130, "stop_org" => "Brachtenbach", "stop" => "Brachtenbach"),
            array("id" => 131, "stop_org" => "Brahmillen", "stop" => "Brahmillen"),
            array("id" => 132, "stop_org" => "Brameschhaff", "stop" => "Brameschhaff"),
            array("id" => 133, "stop_org" => "Brandenbourg", "stop" => "Brandenbourg"),
            array("id" => 134, "stop_org" => "Brattert", "stop" => "Brattert"),
            array("id" => 135, "stop_org" => "Brehm", "stop" => "Brehm"),
            array("id" => 136, "stop_org" => "Breidfeld", "stop" => "Breidfeld"),
            array("id" => 137, "stop_org" => "Breidweiler", "stop" => "Breidweiler"),
            array("id" => 138, "stop_org" => "Breinert", "stop" => "Breinert"),
            array("id" => 139, "stop_org" => "Bricherhaff (Neudorf)", "stop" => "Bricherhaff (Neudorf)"),
            array("id" => 140, "stop_org" => "Bridel", "stop" => "Bridel"),
            array("id" => 141, "stop_org" => "Broderbour", "stop" => "Broderbour"),
            array("id" => 142, "stop_org" => "Brongeshaff", "stop" => "Brongeshaff"),
            array("id" => 143, "stop_org" => "Brosiushaff", "stop" => "Brosiushaff"),
            array("id" => 144, "stop_org" => "Brouch (Mersch)", "stop" => "Brouch (Mersch)"),
            array("id" => 145, "stop_org" => "Brouch (Wecker)", "stop" => "Brouch (Wecker)"),
            array("id" => 146, "stop_org" => "Brouch-Moulin", "stop" => "Brouch-Moulin"),
            array("id" => 147, "stop_org" => "Brücherheck", "stop" => "Brücherheck"),
            array("id" => 148, "stop_org" => "Brücherhof (Folkendange)", "stop" => "Brücherhof (Folkendange)"),
            array("id" => 149, "stop_org" => "Brücherhof (Moutfort)", "stop" => "Brücherhof (Moutfort)"),
            array("id" => 150, "stop_org" => "Brüchermühle (Moutfort)", "stop" => "Brüchermühle (Moutfort)"),
            array("id" => 151, "stop_org" => "Buchholz (Flaxweiler)", "stop" => "Buchholz (Flaxweiler)"),
            array("id" => 152, "stop_org" => "Buchholzerhaff (Dalheim)", "stop" => "Buchholzerhaff (Dalheim)"),
            array("id" => 153, "stop_org" => "Budersberg (Dudelange)", "stop" => "Budersberg (Dudelange)"),
            array("id" => 154, "stop_org" => "Buederscheid", "stop" => "Buederscheid"),
            array("id" => 155, "stop_org" => "Buerghaff", "stop" => "Buerghaff"),
            array("id" => 156, "stop_org" => "Burange (Dudelange)", "stop" => "Burange (Dudelange)"),
            array("id" => 157, "stop_org" => "Burden", "stop" => "Burden"),
            array("id" => 158, "stop_org" => "Burfelt", "stop" => "Burfelt"),
            array("id" => 159, "stop_org" => "Burmerange", "stop" => "Burmerange"),
            array("id" => 160, "stop_org" => "Buschdorf", "stop" => "Buschdorf"),
            array("id" => 161, "stop_org" => "Buschrodt", "stop" => "Buschrodt"),
            array("id" => 162, "stop_org" => "Bücherhof", "stop" => "Bücherhof"),
            array("id" => 163, "stop_org" => "Calmus", "stop" => "Calmus"),
            array("id" => 164, "stop_org" => "Calmus-Moulin", "stop" => "Calmus-Moulin"),
            array("id" => 165, "stop_org" => "Canach", "stop" => "Canach"),
            array("id" => 166, "stop_org" => "Cap", "stop" => "Cap"),
            array("id" => 167, "stop_org" => "Capellen", "stop" => "Capellen"),
            array("id" => 168, "stop_org" => "Carelshaff", "stop" => "Carelshaff"),
            array("id" => 169, "stop_org" => "Cents (Luxembourg)", "stop" => "Cents (Luxembourg)"),
            array("id" => 170, "stop_org" => "Cessange (Luxembourg)", "stop" => "Cessange (Luxembourg)"),
            array("id" => 171, "stop_org" => "Christnach", "stop" => "Christnach"),
            array("id" => 172, "stop_org" => "Cinqfontaines", "stop" => "Cinqfontaines"),
            array("id" => 173, "stop_org" => "Clausen (Luxembourg)", "stop" => "Clausen (Luxembourg)"),
            array("id" => 174, "stop_org" => "Claushof", "stop" => "Claushof"),
            array("id" => 175, "stop_org" => "Clemency", "stop" => "Clemency"),
            array("id" => 176, "stop_org" => "Clemenshaff", "stop" => "Clemenshaff"),
            array("id" => 177, "stop_org" => "Clervaux", "stop" => "Clervaux"),
            array("id" => 178, "stop_org" => "Clervaux- Château", "stop" => "Clervaux- Château"),
            array("id" => 179, "stop_org" => "Cloche d'Or (Luxembourg)", "stop" => "Cloche d'Or (Luxembourg)"),
            array("id" => 180, "stop_org" => "Closbierg", "stop" => "Closbierg"),
            array("id" => 181, "stop_org" => "Closdelt", "stop" => "Closdelt"),
            array("id" => 182, "stop_org" => "Colbette", "stop" => "Colbette"),
            array("id" => 183, "stop_org" => "Colmar", "stop" => "Colmar"),
            array("id" => 184, "stop_org" => "Colmar-Berg", "stop" => "Colmar-Berg"),
            array("id" => 185, "stop_org" => "Colmar-Berg-Halte", "stop" => "Colmar-Berg-Halte"),
            array("id" => 186, "stop_org" => "Colmar-Pont", "stop" => "Colmar-Pont"),
            array("id" => 187, "stop_org" => "Colpach-Bas", "stop" => "Colpach-Bas"),
            array("id" => 188, "stop_org" => "Colpach-Haut", "stop" => "Colpach-Haut"),
            array("id" => 189, "stop_org" => "Consdorf", "stop" => "Consdorf"),
            array("id" => 190, "stop_org" => "Consdorf-Moulin", "stop" => "Consdorf-Moulin"),
            array("id" => 191, "stop_org" => "Consthum", "stop" => "Consthum"),
            array("id" => 192, "stop_org" => "Contern", "stop" => "Contern"),
            array("id" => 193, "stop_org" => "Cornelysmillen", "stop" => "Cornelysmillen"),
            array("id" => 194, "stop_org" => "Crauthem", "stop" => "Crauthem"),
            array("id" => 195, "stop_org" => "Crendal", "stop" => "Crendal"),
            array("id" => 196, "stop_org" => "Cruchten", "stop" => "Cruchten"),
            array("id" => 197, "stop_org" => "Dahl", "stop" => "Dahl"),
            array("id" => 198, "stop_org" => "Dahlem", "stop" => "Dahlem"),
            array("id" => 199, "stop_org" => "Dalheim", "stop" => "Dalheim"),
            array("id" => 200, "stop_org" => "Dasbourg-Pont", "stop" => "Dasbourg-Pont"),
            array("id" => 201, "stop_org" => "Deiffelt", "stop" => "Deiffelt"),
            array("id" => 202, "stop_org" => "Dellen", "stop" => "Dellen"),
            array("id" => 203, "stop_org" => "Derenbach", "stop" => "Derenbach"),
            array("id" => 204, "stop_org" => "Deysermühle", "stop" => "Deysermühle"),
            array("id" => 205, "stop_org" => "Dickeschbur", "stop" => "Dickeschbur"),
            array("id" => 206, "stop_org" => "Dickweiler", "stop" => "Dickweiler"),
            array("id" => 207, "stop_org" => "Diekirch", "stop" => "Diekirch"),
            array("id" => 208, "stop_org" => "Differdange", "stop" => "Differdange"),
            array("id" => 209, "stop_org" => "Dillingen", "stop" => "Dillingen"),
            array("id" => 210, "stop_org" => "Dippach", "stop" => "Dippach"),
            array("id" => 211, "stop_org" => "Dippach-Gare", "stop" => "Dippach-Gare"),
            array("id" => 212, "stop_org" => "Dippach-Haard", "stop" => "Dippach-Haard"),
            array("id" => 213, "stop_org" => "Dirbach", "stop" => "Dirbach"),
            array("id" => 214, "stop_org" => "Dirbach (Goesdorf)", "stop" => "Dirbach (Goesdorf)"),
            array("id" => 215, "stop_org" => "Doennange", "stop" => "Doennange"),
            array("id" => 216, "stop_org" => "Domaine d'Olm", "stop" => "Domaine d'Olm"),
            array("id" => 217, "stop_org" => "Dommeldange (Luxembourg)", "stop" => "Dommeldange (Luxembourg)"),
            array("id" => 218, "stop_org" => "Doncols", "stop" => "Doncols"),
            array("id" => 219, "stop_org" => "Dondelange", "stop" => "Dondelange"),
            array("id" => 220, "stop_org" => "Dorscheid", "stop" => "Dorscheid"),
            array("id" => 221, "stop_org" => "Dorscheiderhaischen", "stop" => "Dorscheiderhaischen"),
            array("id" => 222, "stop_org" => "Dosterthaff / Dousterterhaff", "stop" => "Dosterthaff / Dousterterhaff"),
            array("id" => 223, "stop_org" => "Drauffelt", "stop" => "Drauffelt"),
            array("id" => 224, "stop_org" => "Dreiborn", "stop" => "Dreiborn"),
            array("id" => 225, "stop_org" => "Drinklange", "stop" => "Drinklange"),
            array("id" => 226, "stop_org" => "Dudderhaff", "stop" => "Dudderhaff"),
            array("id" => 227, "stop_org" => "Dudelange", "stop" => "Dudelange"),
            array("id" => 228, "stop_org" => "Dumontshaff / Dumongshaff", "stop" => "Dumontshaff / Dumongshaff"),
            array("id" => 229, "stop_org" => "Durenthal", "stop" => "Durenthal"),
            array("id" => 230, "stop_org" => "ELL", "stop" => "ELL"),
            array("id" => 231, "stop_org" => "Echternach", "stop" => "Echternach"),
            array("id" => 232, "stop_org" => "Ehlange", "stop" => "Ehlange"),
            array("id" => 233, "stop_org" => "Ehlerange", "stop" => "Ehlerange"),
            array("id" => 234, "stop_org" => "Ehnen", "stop" => "Ehnen"),
            array("id" => 235, "stop_org" => "Ehner", "stop" => "Ehner"),
            array("id" => 236, "stop_org" => "Eich (Luxembourg)", "stop" => "Eich (Luxembourg)"),
            array("id" => 237, "stop_org" => "Eichelbour", "stop" => "Eichelbour"),
            array("id" => 238, "stop_org" => "Eischen", "stop" => "Eischen"),
            array("id" => 239, "stop_org" => "Eisenbach", "stop" => "Eisenbach"),
            array("id" => 240, "stop_org" => "Eisenborn", "stop" => "Eisenborn"),
            array("id" => 241, "stop_org" => "Ellange", "stop" => "Ellange"),
            array("id" => 242, "stop_org" => "Ellange-Gare", "stop" => "Ellange-Gare"),
            array("id" => 243, "stop_org" => "Eltz", "stop" => "Eltz"),
            array("id" => 244, "stop_org" => "Elvange", "stop" => "Elvange"),
            array("id" => 245, "stop_org" => "Elvange (Schengen)", "stop" => "Elvange (Schengen)"),
            array("id" => 246, "stop_org" => "Emerange", "stop" => "Emerange"),
            array("id" => 247, "stop_org" => "Emeringerhaff / Éimeréngerhaff", "stop" => "Emeringerhaff / Éimeréngerhaff"),
            array("id" => 248, "stop_org" => "Emeschbach Asselborn", "stop" => "Emeschbach Asselborn"),
            array("id" => 249, "stop_org" => "Engelshaff", "stop" => "Engelshaff"),
            array("id" => 250, "stop_org" => "Enscherange", "stop" => "Enscherange"),
            array("id" => 251, "stop_org" => "Enteschbach", "stop" => "Enteschbach"),
            array("id" => 252, "stop_org" => "Eppeldorf", "stop" => "Eppeldorf"),
            array("id" => 253, "stop_org" => "Ermsdorf", "stop" => "Ermsdorf"),
            array("id" => 254, "stop_org" => "Ernster", "stop" => "Ernster"),
            array("id" => 255, "stop_org" => "Ernzen", "stop" => "Ernzen"),
            array("id" => 256, "stop_org" => "Erpeldange (Bous)", "stop" => "Erpeldange (Bous)"),
            array("id" => 257, "stop_org" => "Erpeldange (Eschweiler)", "stop" => "Erpeldange (Eschweiler)"),
            array("id" => 258, "stop_org" => "Erpeldange-sur-Sûre", "stop" => "Erpeldange-sur-Sûre"),
            array("id" => 259, "stop_org" => "Ersange", "stop" => "Ersange"),
            array("id" => 260, "stop_org" => "Esch-Belval", "stop" => "Esch-Belval"),
            array("id" => 261, "stop_org" => "Esch-sur-Alzette", "stop" => "Esch-sur-Alzette"),
            array("id" => 262, "stop_org" => "Esch-sur-Sûre", "stop" => "Esch-sur-Sûre"),
            array("id" => 263, "stop_org" => "Eschdorf", "stop" => "Eschdorf"),
            array("id" => 264, "stop_org" => "Eschette", "stop" => "Eschette"),
            array("id" => 265, "stop_org" => "Eschweiler", "stop" => "Eschweiler"),
            array("id" => 266, "stop_org" => "Eschweiler (Wiltz)", "stop" => "Eschweiler (Wiltz)"),
            array("id" => 267, "stop_org" => "Eschweiler-Halte", "stop" => "Eschweiler-Halte"),
            array("id" => 268, "stop_org" => "Eselborn", "stop" => "Eselborn"),
            array("id" => 269, "stop_org" => "Essingen", "stop" => "Essingen"),
            array("id" => 270, "stop_org" => "Ettelbruck", "stop" => "Ettelbruck"),
            array("id" => 271, "stop_org" => "Everlange", "stop" => "Everlange"),
            array("id" => 272, "stop_org" => "Everlange-Moulin", "stop" => "Everlange-Moulin"),
            array("id" => 273, "stop_org" => "FEULEN", "stop" => "FEULEN"),
            array("id" => 274, "stop_org" => "Fausermillen", "stop" => "Fausermillen"),
            array("id" => 275, "stop_org" => "Felleschmillen", "stop" => "Felleschmillen"),
            array("id" => 276, "stop_org" => "Fennange", "stop" => "Fennange"),
            array("id" => 277, "stop_org" => "Fentange", "stop" => "Fentange"),
            array("id" => 278, "stop_org" => "Ferme rouge (Rodange)", "stop" => "Ferme rouge (Rodange)"),
            array("id" => 279, "stop_org" => "Fetschenhof (Luxembourg)", "stop" => "Fetschenhof (Luxembourg)"),
            array("id" => 280, "stop_org" => "Fielsmillen (Echternach)", "stop" => "Fielsmillen (Echternach)"),
            array("id" => 281, "stop_org" => "Fielsmillen (Mertert)", "stop" => "Fielsmillen (Mertert)"),
            array("id" => 282, "stop_org" => "Filsdorf", "stop" => "Filsdorf"),
            array("id" => 283, "stop_org" => "Findel", "stop" => "Findel"),
            array("id" => 284, "stop_org" => "Findels (Ferme de)", "stop" => "Findels (Ferme de)"),
            array("id" => 285, "stop_org" => "Fingig", "stop" => "Fingig"),
            array("id" => 286, "stop_org" => "Finsterthal", "stop" => "Finsterthal"),
            array("id" => 287, "stop_org" => "Firtgeshaff", "stop" => "Firtgeshaff"),
            array("id" => 288, "stop_org" => "Fischbach", "stop" => "Fischbach"),
            array("id" => 289, "stop_org" => "Fischbach (Clervaux)", "stop" => "Fischbach (Clervaux)"),
            array("id" => 290, "stop_org" => "Fischbacherhaff", "stop" => "Fischbacherhaff"),
            array("id" => 291, "stop_org" => "Flatzbour", "stop" => "Flatzbour"),
            array("id" => 292, "stop_org" => "Flaxweiler", "stop" => "Flaxweiler"),
            array("id" => 293, "stop_org" => "Flebour", "stop" => "Flebour"),
            array("id" => 294, "stop_org" => "Flebour (Baschleiden)", "stop" => "Flebour (Baschleiden)"),
            array("id" => 295, "stop_org" => "Flickenhaff / Fleckenhaff", "stop" => "Flickenhaff / Fleckenhaff"),
            array("id" => 296, "stop_org" => "Fockemillen", "stop" => "Fockemillen"),
            array("id" => 297, "stop_org" => "Foetz", "stop" => "Foetz"),
            array("id" => 298, "stop_org" => "Folkendange", "stop" => "Folkendange"),
            array("id" => 299, "stop_org" => "Follmillen", "stop" => "Follmillen"),
            array("id" => 300, "stop_org" => "Folschette", "stop" => "Folschette"),
            array("id" => 301, "stop_org" => "Fond de Gras", "stop" => "Fond de Gras"),
            array("id" => 302, "stop_org" => "Fossenhof", "stop" => "Fossenhof"),
            array("id" => 303, "stop_org" => "Fouhren", "stop" => "Fouhren"),
            array("id" => 304, "stop_org" => "Fousbann (Differdange)", "stop" => "Fousbann (Differdange)"),
            array("id" => 305, "stop_org" => "Freckeisen", "stop" => "Freckeisen"),
            array("id" => 306, "stop_org" => "Freresmühle", "stop" => "Freresmühle"),
            array("id" => 307, "stop_org" => "Fridhaff", "stop" => "Fridhaff"),
            array("id" => 308, "stop_org" => "Friedbusch", "stop" => "Friedbusch"),
            array("id" => 309, "stop_org" => "Frisange", "stop" => "Frisange"),
            array("id" => 310, "stop_org" => "Frombuerg / Fromburgerhaff", "stop" => "Frombuerg / Fromburgerhaff"),
            array("id" => 311, "stop_org" => "Froumillen", "stop" => "Froumillen"),
            array("id" => 312, "stop_org" => "Fréngerhaff", "stop" => "Fréngerhaff"),
            array("id" => 313, "stop_org" => "Furels", "stop" => "Furels"),
            array("id" => 314, "stop_org" => "Fuussekaul", "stop" => "Fuussekaul"),
            array("id" => 315, "stop_org" => "Fuusswiss", "stop" => "Fuusswiss"),
            array("id" => 316, "stop_org" => "Féischterbierg", "stop" => "Féischterbierg"),
            array("id" => 317, "stop_org" => "Féischterhaff", "stop" => "Féischterhaff"),
            array("id" => 318, "stop_org" => "Féitsch", "stop" => "Féitsch"),
            array("id" => 319, "stop_org" => "Fënsterhaff", "stop" => "Fënsterhaff"),
            array("id" => 320, "stop_org" => "Fënz", "stop" => "Fënz"),
            array("id" => 321, "stop_org" => "Gaaschtmillen", "stop" => "Gaaschtmillen"),
            array("id" => 322, "stop_org" => "Gaichel", "stop" => "Gaichel"),
            array("id" => 323, "stop_org" => "Gantebeensmillen", "stop" => "Gantebeensmillen"),
            array("id" => 324, "stop_org" => "Garnich", "stop" => "Garnich"),
            array("id" => 325, "stop_org" => "Gasperich (Luxembourg)", "stop" => "Gasperich (Luxembourg)"),
            array("id" => 326, "stop_org" => "Geierhaff (Holzthum)", "stop" => "Geierhaff (Holzthum)"),
            array("id" => 327, "stop_org" => "Geyershof (Bech)", "stop" => "Geyershof (Bech)"),
            array("id" => 328, "stop_org" => "Gillenshaff", "stop" => "Gillenshaff"),
            array("id" => 329, "stop_org" => "Gilsdorf", "stop" => "Gilsdorf"),
            array("id" => 330, "stop_org" => "Girst", "stop" => "Girst"),
            array("id" => 331, "stop_org" => "Girsterklaus", "stop" => "Girsterklaus"),
            array("id" => 332, "stop_org" => "Givenich", "stop" => "Givenich"),
            array("id" => 333, "stop_org" => "Goberhaff", "stop" => "Goberhaff"),
            array("id" => 334, "stop_org" => "Godbrange", "stop" => "Godbrange"),
            array("id" => 335, "stop_org" => "Goebelsmuehle", "stop" => "Goebelsmuehle"),
            array("id" => 336, "stop_org" => "Goebelsmühle", "stop" => "Goebelsmühle"),
            array("id" => 337, "stop_org" => "Goeblange", "stop" => "Goeblange"),
            array("id" => 338, "stop_org" => "Goedange", "stop" => "Goedange"),
            array("id" => 339, "stop_org" => "Goedange-Moulin", "stop" => "Goedange-Moulin"),
            array("id" => 340, "stop_org" => "Goelt", "stop" => "Goelt"),
            array("id" => 341, "stop_org" => "Goesdorf", "stop" => "Goesdorf"),
            array("id" => 342, "stop_org" => "Goetzingen", "stop" => "Goetzingen"),
            array("id" => 343, "stop_org" => "Gondelange", "stop" => "Gondelange"),
            array("id" => 344, "stop_org" => "Gonderange", "stop" => "Gonderange"),
            array("id" => 345, "stop_org" => "Gosseldange", "stop" => "Gosseldange"),
            array("id" => 346, "stop_org" => "Gostingen", "stop" => "Gostingen"),
            array("id" => 347, "stop_org" => "Goudelt", "stop" => "Goudelt"),
            array("id" => 348, "stop_org" => "Gralingen", "stop" => "Gralingen"),
            array("id" => 349, "stop_org" => "Grand-Bevange (Hivange)", "stop" => "Grand-Bevange (Hivange)"),
            array("id" => 350, "stop_org" => "Grass", "stop" => "Grass"),
            array("id" => 351, "stop_org" => "Grassbusch (Leudelange)", "stop" => "Grassbusch (Leudelange)"),
            array("id" => 352, "stop_org" => "Grauenstein", "stop" => "Grauenstein"),
            array("id" => 353, "stop_org" => "Graulinster", "stop" => "Graulinster"),
            array("id" => 354, "stop_org" => "Graulinster (Bech)", "stop" => "Graulinster (Bech)"),
            array("id" => 355, "stop_org" => "Greisch", "stop" => "Greisch"),
            array("id" => 356, "stop_org" => "Greiveldange", "stop" => "Greiveldange"),
            array("id" => 357, "stop_org" => "Grentzingen", "stop" => "Grentzingen"),
            array("id" => 358, "stop_org" => "Grevels", "stop" => "Grevels"),
            array("id" => 359, "stop_org" => "Grevels (Ferme de) (Bertrange)", "stop" => "Grevels (Ferme de) (Bertrange)"),
            array("id" => 360, "stop_org" => "Grevels (Grosbous)", "stop" => "Grevels (Grosbous)"),
            array("id" => 361, "stop_org" => "Grevels - Nei-Brésil", "stop" => "Grevels - Nei-Brésil"),
            array("id" => 362, "stop_org" => "Grevelsbarrière (Bertrange)", "stop" => "Grevelsbarrière (Bertrange)"),
            array("id" => 363, "stop_org" => "Grevenhaff", "stop" => "Grevenhaff"),
            array("id" => 364, "stop_org" => "Grevenknapp", "stop" => "Grevenknapp"),
            array("id" => 365, "stop_org" => "Grevenmacher", "stop" => "Grevenmacher"),
            array("id" => 366, "stop_org" => "Grindhausen", "stop" => "Grindhausen"),
            array("id" => 367, "stop_org" => "Grosbous", "stop" => "Grosbous"),
            array("id" => 368, "stop_org" => "Gruemelscheid", "stop" => "Gruemelscheid"),
            array("id" => 369, "stop_org" => "Grund (Luxembourg)", "stop" => "Grund (Luxembourg)"),
            array("id" => 370, "stop_org" => "Grundhof", "stop" => "Grundhof"),
            array("id" => 371, "stop_org" => "Grundhof (Berdorf)", "stop" => "Grundhof (Berdorf)"),
            array("id" => 372, "stop_org" => "Grundhof - Château", "stop" => "Grundhof - Château"),
            array("id" => 373, "stop_org" => "Haanenhaff", "stop" => "Haanenhaff"),
            array("id" => 374, "stop_org" => "Haarderbaach", "stop" => "Haarderbaach"),
            array("id" => 375, "stop_org" => "Hachiville", "stop" => "Hachiville"),
            array("id" => 376, "stop_org" => "Hagelsdorf", "stop" => "Hagelsdorf"),
            array("id" => 377, "stop_org" => "Hagen", "stop" => "Hagen"),
            array("id" => 378, "stop_org" => "Hakenhaff", "stop" => "Hakenhaff"),
            array("id" => 379, "stop_org" => "Haller", "stop" => "Haller"),
            array("id" => 380, "stop_org" => "Halsbaach", "stop" => "Halsbaach"),
            array("id" => 381, "stop_org" => "Hamiville", "stop" => "Hamiville"),
            array("id" => 382, "stop_org" => "Hamm (Luxembourg)", "stop" => "Hamm (Luxembourg)"),
            array("id" => 383, "stop_org" => "Hammhaff", "stop" => "Hammhaff"),
            array("id" => 384, "stop_org" => "Hardhaff", "stop" => "Hardhaff"),
            array("id" => 385, "stop_org" => "Harlange", "stop" => "Harlange"),
            array("id" => 386, "stop_org" => "Harlange-Poteau", "stop" => "Harlange-Poteau"),
            array("id" => 387, "stop_org" => "Hassel", "stop" => "Hassel"),
            array("id" => 388, "stop_org" => "Haut-Martelange", "stop" => "Haut-Martelange"),
            array("id" => 389, "stop_org" => "Hautbellain", "stop" => "Hautbellain"),
            array("id" => 390, "stop_org" => "Hautcharage", "stop" => "Hautcharage"),
            array("id" => 391, "stop_org" => "Heckenhaff", "stop" => "Heckenhaff"),
            array("id" => 392, "stop_org" => "Heffingen", "stop" => "Heffingen"),
            array("id" => 393, "stop_org" => "Heiderscheid", "stop" => "Heiderscheid"),
            array("id" => 394, "stop_org" => "Heiderscheidergrund", "stop" => "Heiderscheidergrund"),
            array("id" => 395, "stop_org" => "Heiderscheidergrund (Goesdorf)", "stop" => "Heiderscheidergrund (Goesdorf)"),
            array("id" => 396, "stop_org" => "Heidscheuer", "stop" => "Heidscheuer"),
            array("id" => 397, "stop_org" => "Heinenhaff", "stop" => "Heinenhaff"),
            array("id" => 398, "stop_org" => "Heinerscheid", "stop" => "Heinerscheid"),
            array("id" => 399, "stop_org" => "Heisbich", "stop" => "Heisbich"),
            array("id" => 400, "stop_org" => "Heisburgerhaff / Heesberhaff", "stop" => "Heisburgerhaff / Heesberhaff"),
            array("id" => 401, "stop_org" => "Heisdorf", "stop" => "Heisdorf"),
            array("id" => 402, "stop_org" => "Heispelt", "stop" => "Heispelt"),
            array("id" => 403, "stop_org" => "Helfent (Bertrange)", "stop" => "Helfent (Bertrange)"),
            array("id" => 404, "stop_org" => "Hellange", "stop" => "Hellange"),
            array("id" => 405, "stop_org" => "Hellgewiss", "stop" => "Hellgewiss"),
            array("id" => 406, "stop_org" => "Helmdange", "stop" => "Helmdange"),
            array("id" => 407, "stop_org" => "Helmsange", "stop" => "Helmsange"),
            array("id" => 408, "stop_org" => "Hemstal", "stop" => "Hemstal"),
            array("id" => 409, "stop_org" => "Herborn", "stop" => "Herborn"),
            array("id" => 410, "stop_org" => "Herborn-Moulin", "stop" => "Herborn-Moulin"),
            array("id" => 411, "stop_org" => "Herdermillen", "stop" => "Herdermillen"),
            array("id" => 412, "stop_org" => "Hermeswiss", "stop" => "Hermeswiss"),
            array("id" => 413, "stop_org" => "Herrenberg", "stop" => "Herrenberg"),
            array("id" => 414, "stop_org" => "Hersberg", "stop" => "Hersberg"),
            array("id" => 415, "stop_org" => "Hesperange", "stop" => "Hesperange"),
            array("id" => 416, "stop_org" => "Hessemillen", "stop" => "Hessemillen"),
            array("id" => 417, "stop_org" => "Hierheck", "stop" => "Hierheck"),
            array("id" => 418, "stop_org" => "Hiestgriechterhof", "stop" => "Hiestgriechterhof"),
            array("id" => 419, "stop_org" => "Hingerhaff", "stop" => "Hingerhaff"),
            array("id" => 420, "stop_org" => "Hinkel", "stop" => "Hinkel"),
            array("id" => 421, "stop_org" => "Hinterhassel", "stop" => "Hinterhassel"),
            array("id" => 422, "stop_org" => "Hirtzhaff (Feulen)", "stop" => "Hirtzhaff (Feulen)"),
            array("id" => 423, "stop_org" => "Hirzenhaff (Bettendorf)", "stop" => "Hirzenhaff (Bettendorf)"),
            array("id" => 424, "stop_org" => "Hivange", "stop" => "Hivange"),
            array("id" => 425, "stop_org" => "Hobscheid", "stop" => "Hobscheid"),
            array("id" => 426, "stop_org" => "Hoesdorf", "stop" => "Hoesdorf"),
            array("id" => 427, "stop_org" => "Hof Ahl", "stop" => "Hof Ahl"),
            array("id" => 428, "stop_org" => "Hoffelt", "stop" => "Hoffelt"),
            array("id" => 429, "stop_org" => "Hollenfels", "stop" => "Hollenfels"),
            array("id" => 430, "stop_org" => "Holler", "stop" => "Holler"),
            array("id" => 431, "stop_org" => "Hollerich (Luxembourg)", "stop" => "Hollerich (Luxembourg)"),
            array("id" => 432, "stop_org" => "Hollermühle", "stop" => "Hollermühle"),
            array("id" => 433, "stop_org" => "Holtz", "stop" => "Holtz"),
            array("id" => 434, "stop_org" => "Holzem", "stop" => "Holzem"),
            array("id" => 435, "stop_org" => "Holzthum", "stop" => "Holzthum"),
            array("id" => 436, "stop_org" => "Hongeschhaff", "stop" => "Hongeschhaff"),
            array("id" => 437, "stop_org" => "Honicht", "stop" => "Honicht"),
            array("id" => 438, "stop_org" => "Horas", "stop" => "Horas"),
            array("id" => 439, "stop_org" => "Horgershaff", "stop" => "Horgershaff"),
            array("id" => 440, "stop_org" => "Hosbich", "stop" => "Hosbich"),
            array("id" => 441, "stop_org" => "Hoscheid", "stop" => "Hoscheid"),
            array("id" => 442, "stop_org" => "Hoscheid-Dickt", "stop" => "Hoscheid-Dickt"),
            array("id" => 443, "stop_org" => "Hoscheidterhof", "stop" => "Hoscheidterhof"),
            array("id" => 444, "stop_org" => "Hosingen", "stop" => "Hosingen"),
            array("id" => 445, "stop_org" => "Hosingen-Barrière", "stop" => "Hosingen-Barrière"),
            array("id" => 446, "stop_org" => "Hossenberg", "stop" => "Hossenberg"),
            array("id" => 447, "stop_org" => "Hostert (Folschette)", "stop" => "Hostert (Folschette)"),
            array("id" => 448, "stop_org" => "Hostert (Senningerberg)", "stop" => "Hostert (Senningerberg)"),
            array("id" => 449, "stop_org" => "Hovelange", "stop" => "Hovelange"),
            array("id" => 450, "stop_org" => "Howald", "stop" => "Howald"),
            array("id" => 451, "stop_org" => "Hubertushof", "stop" => "Hubertushof"),
            array("id" => 452, "stop_org" => "Huettermuehle", "stop" => "Huettermuehle"),
            array("id" => 453, "stop_org" => "Huldange", "stop" => "Huldange"),
            array("id" => 454, "stop_org" => "Huldange-Forge", "stop" => "Huldange-Forge"),
            array("id" => 455, "stop_org" => "Huldange-Moulin", "stop" => "Huldange-Moulin"),
            array("id" => 456, "stop_org" => "Huncherange", "stop" => "Huncherange"),
            array("id" => 457, "stop_org" => "Hunnebur", "stop" => "Hunnebur"),
            array("id" => 458, "stop_org" => "Hunsdorf", "stop" => "Hunsdorf"),
            array("id" => 459, "stop_org" => "Hupperdange", "stop" => "Hupperdange"),
            array("id" => 460, "stop_org" => "Huttange", "stop" => "Huttange"),
            array("id" => 461, "stop_org" => "Imbringen", "stop" => "Imbringen"),
            array("id" => 462, "stop_org" => "Ingeldorf", "stop" => "Ingeldorf"),
            array("id" => 463, "stop_org" => "Insenborn", "stop" => "Insenborn"),
            array("id" => 464, "stop_org" => "Itzig", "stop" => "Itzig"),
            array("id" => 465, "stop_org" => "Itzigerste", "stop" => "Itzigerste"),
            array("id" => 466, "stop_org" => "Jaanshaff", "stop" => "Jaanshaff"),
            array("id" => 467, "stop_org" => "Jakobsbierg", "stop" => "Jakobsbierg"),
            array("id" => 468, "stop_org" => "Jean-Haris", "stop" => "Jean-Haris"),
            array("id" => 469, "stop_org" => "Jemenerhaff", "stop" => "Jemenerhaff"),
            array("id" => 470, "stop_org" => "Juckefeld", "stop" => "Juckefeld"),
            array("id" => 471, "stop_org" => "Juegdschlass (Baambësch)", "stop" => "Juegdschlass (Baambësch)"),
            array("id" => 472, "stop_org" => "Juegdschlass (Koerich)", "stop" => "Juegdschlass (Koerich)"),
            array("id" => 473, "stop_org" => "Junglinster", "stop" => "Junglinster"),
            array("id" => 474, "stop_org" => "Jäger (Maison-)", "stop" => "Jäger (Maison-)"),
            array("id" => 475, "stop_org" => "Jénkenhaff", "stop" => "Jénkenhaff"),
            array("id" => 476, "stop_org" => "Kaaspelt", "stop" => "Kaaspelt"),
            array("id" => 477, "stop_org" => "Kackerterhaff", "stop" => "Kackerterhaff"),
            array("id" => 478, "stop_org" => "Kaesfurt", "stop" => "Kaesfurt"),
            array("id" => 479, "stop_org" => "Kaffishaff", "stop" => "Kaffishaff"),
            array("id" => 480, "stop_org" => "Kahler", "stop" => "Kahler"),
            array("id" => 481, "stop_org" => "Kalborn", "stop" => "Kalborn"),
            array("id" => 482, "stop_org" => "Kalborn-Moulin", "stop" => "Kalborn-Moulin"),
            array("id" => 483, "stop_org" => "Kalchesbréck", "stop" => "Kalchesbréck"),
            array("id" => 484, "stop_org" => "Kalkesbach (Berdorf)", "stop" => "Kalkesbach (Berdorf)"),
            array("id" => 485, "stop_org" => "Kalkesbach (Consdorf)", "stop" => "Kalkesbach (Consdorf)"),
            array("id" => 486, "stop_org" => "Kalscheier", "stop" => "Kalscheier"),
            array("id" => 487, "stop_org" => "Kapenacker", "stop" => "Kapenacker"),
            array("id" => 488, "stop_org" => "Kapweiler", "stop" => "Kapweiler"),
            array("id" => 489, "stop_org" => "Kaundorf", "stop" => "Kaundorf"),
            array("id" => 490, "stop_org" => "Kautenbach", "stop" => "Kautenbach"),
            array("id" => 491, "stop_org" => "Kayl", "stop" => "Kayl"),
            array("id" => 492, "stop_org" => "Kehlen", "stop" => "Kehlen"),
            array("id" => 493, "stop_org" => "Kehmen", "stop" => "Kehmen"),
            array("id" => 494, "stop_org" => "Keispelt", "stop" => "Keispelt"),
            array("id" => 495, "stop_org" => "Keiwelbach", "stop" => "Keiwelbach"),
            array("id" => 496, "stop_org" => "Kelleschhaff", "stop" => "Kelleschhaff"),
            array("id" => 497, "stop_org" => "Kemicht", "stop" => "Kemicht"),
            array("id" => 498, "stop_org" => "Kempchen", "stop" => "Kempchen"),
            array("id" => 499, "stop_org" => "Kempemillen", "stop" => "Kempemillen"),
            array("id" => 500, "stop_org" => "Kengert", "stop" => "Kengert"),
            array("id" => 501, "stop_org" => "Kenseckehaff", "stop" => "Kenseckehaff"),
            array("id" => 502, "stop_org" => "Kiemerchen", "stop" => "Kiemerchen"),
            array("id" => 503, "stop_org" => "Kiirchermillen", "stop" => "Kiirchermillen"),
            array("id" => 504, "stop_org" => "Kimm", "stop" => "Kimm"),
            array("id" => 505, "stop_org" => "Kinnekshaff", "stop" => "Kinnekshaff"),
            array("id" => 506, "stop_org" => "Kirchberg (Luxembourg)", "stop" => "Kirchberg (Luxembourg)"),
            array("id" => 507, "stop_org" => "Kirchberg-Centre Européen", "stop" => "Kirchberg-Centre Européen"),
            array("id" => 508, "stop_org" => "Kirelshaff", "stop" => "Kirelshaff"),
            array("id" => 509, "stop_org" => "Kitzebur", "stop" => "Kitzebur"),
            array("id" => 510, "stop_org" => "Klaus (Wolwelange)", "stop" => "Klaus (Wolwelange)"),
            array("id" => 511, "stop_org" => "Klaushaff (Septfontaines)", "stop" => "Klaushaff (Septfontaines)"),
            array("id" => 512, "stop_org" => "Kleinbettingen", "stop" => "Kleinbettingen"),
            array("id" => 513, "stop_org" => "Kleinhoscheid", "stop" => "Kleinhoscheid"),
            array("id" => 514, "stop_org" => "Klenge Buerghaff / Klengbuerghaff", "stop" => "Klenge Buerghaff / Klengbuerghaff"),
            array("id" => 515, "stop_org" => "Klingelscheuer", "stop" => "Klingelscheuer"),
            array("id" => 516, "stop_org" => "Klosmillen", "stop" => "Klosmillen"),
            array("id" => 517, "stop_org" => "Kléck", "stop" => "Kléck"),
            array("id" => 518, "stop_org" => "Kléimillen", "stop" => "Kléimillen"),
            array("id" => 519, "stop_org" => "Kléngelbur", "stop" => "Kléngelbur"),
            array("id" => 520, "stop_org" => "Knaphoscheid", "stop" => "Knaphoscheid"),
            array("id" => 521, "stop_org" => "Kobenbour", "stop" => "Kobenbour"),
            array("id" => 522, "stop_org" => "Kockelscheuer", "stop" => "Kockelscheuer"),
            array("id" => 523, "stop_org" => "Koedange", "stop" => "Koedange"),
            array("id" => 524, "stop_org" => "Koerich", "stop" => "Koerich"),
            array("id" => 525, "stop_org" => "Koetschette", "stop" => "Koetschette"),
            array("id" => 526, "stop_org" => "Kohn", "stop" => "Kohn"),
            array("id" => 527, "stop_org" => "Konerhaff (Alscheid)", "stop" => "Konerhaff (Alscheid)"),
            array("id" => 528, "stop_org" => "Kopstal", "stop" => "Kopstal"),
            array("id" => 529, "stop_org" => "Kounenhaff (Obereisenbach)", "stop" => "Kounenhaff (Obereisenbach)"),
            array("id" => 530, "stop_org" => "Krakelshaff (Bettembourg)", "stop" => "Krakelshaff (Bettembourg)"),
            array("id" => 531, "stop_org" => "Kranzenhaff", "stop" => "Kranzenhaff"),
            array("id" => 532, "stop_org" => "Kraïzenheicht", "stop" => "Kraïzenheicht"),
            array("id" => 533, "stop_org" => "Kreuzerbuch", "stop" => "Kreuzerbuch"),
            array("id" => 534, "stop_org" => "Kroentgeshof", "stop" => "Kroentgeshof"),
            array("id" => 535, "stop_org" => "Krokelshaff (Aspelt)", "stop" => "Krokelshaff (Aspelt)"),
            array("id" => 536, "stop_org" => "Kräizhaff", "stop" => "Kräizhaff"),
            array("id" => 537, "stop_org" => "Kuborn", "stop" => "Kuborn"),
            array("id" => 538, "stop_org" => "Kuelbecherhaff", "stop" => "Kuelbecherhaff"),
            array("id" => 539, "stop_org" => "Kultgeshaff", "stop" => "Kultgeshaff"),
            array("id" => 540, "stop_org" => "Käsfurt", "stop" => "Käsfurt"),
            array("id" => 541, "stop_org" => "Käsfurt (Beiler)", "stop" => "Käsfurt (Beiler)"),
            array("id" => 542, "stop_org" => "Kéiermillen", "stop" => "Kéiermillen"),
            array("id" => 543, "stop_org" => "Këppenhaff", "stop" => "Këppenhaff"),
            array("id" => 544, "stop_org" => "Köppenhaff", "stop" => "Köppenhaff"),
            array("id" => 545, "stop_org" => "LAC DE LA HAUTE SÛRE", "stop" => "LAC DE LA HAUTE SÛRE"),
            array("id" => 546, "stop_org" => "Lafewier", "stop" => "Lafewier"),
            array("id" => 547, "stop_org" => "Lallange (Esch-sur-Alzette)", "stop" => "Lallange (Esch-sur-Alzette)"),
            array("id" => 548, "stop_org" => "Lamadelaine", "stop" => "Lamadelaine"),
            array("id" => 549, "stop_org" => "Lameschermillen (Bergem)", "stop" => "Lameschermillen (Bergem)"),
            array("id" => 550, "stop_org" => "Lameschmillen (Wiltz)", "stop" => "Lameschmillen (Wiltz)"),
            array("id" => 551, "stop_org" => "Landscheid", "stop" => "Landscheid"),
            array("id" => 552, "stop_org" => "Lannen", "stop" => "Lannen"),
            array("id" => 553, "stop_org" => "Lannenerbierg", "stop" => "Lannenerbierg"),
            array("id" => 554, "stop_org" => "Larochette", "stop" => "Larochette"),
            array("id" => 555, "stop_org" => "Larochette - Château", "stop" => "Larochette - Château"),
            array("id" => 556, "stop_org" => "Lasauvage", "stop" => "Lasauvage"),
            array("id" => 557, "stop_org" => "Lausdorn", "stop" => "Lausdorn"),
            array("id" => 558, "stop_org" => "Lausdorn (Heinerscheid)", "stop" => "Lausdorn (Heinerscheid)"),
            array("id" => 559, "stop_org" => "Lauterborn", "stop" => "Lauterborn"),
            array("id" => 560, "stop_org" => "Leesbach", "stop" => "Leesbach"),
            array("id" => 561, "stop_org" => "Legay (Maison -)", "stop" => "Legay (Maison -)"),
            array("id" => 562, "stop_org" => "Lehmkaul", "stop" => "Lehmkaul"),
            array("id" => 563, "stop_org" => "Lehrhof", "stop" => "Lehrhof"),
            array("id" => 564, "stop_org" => "Leidenbach", "stop" => "Leidenbach"),
            array("id" => 565, "stop_org" => "Leithum", "stop" => "Leithum"),
            array("id" => 566, "stop_org" => "Leitrange", "stop" => "Leitrange"),
            array("id" => 567, "stop_org" => "Lellig", "stop" => "Lellig"),
            array("id" => 568, "stop_org" => "Lellingen", "stop" => "Lellingen"),
            array("id" => 569, "stop_org" => "Lellingerhof", "stop" => "Lellingerhof"),
            array("id" => 570, "stop_org" => "Lenglerlach", "stop" => "Lenglerlach"),
            array("id" => 571, "stop_org" => "Lenningen", "stop" => "Lenningen"),
            array("id" => 572, "stop_org" => "Lentzweiler", "stop" => "Lentzweiler"),
            array("id" => 573, "stop_org" => "Les Rochers", "stop" => "Les Rochers"),
            array("id" => 574, "stop_org" => "Leudelange", "stop" => "Leudelange"),
            array("id" => 575, "stop_org" => "Leudelange-Gare", "stop" => "Leudelange-Gare"),
            array("id" => 576, "stop_org" => "Levelange", "stop" => "Levelange"),
            array("id" => 577, "stop_org" => "Leymühle", "stop" => "Leymühle"),
            array("id" => 578, "stop_org" => "Liefrange", "stop" => "Liefrange"),
            array("id" => 579, "stop_org" => "Lieler", "stop" => "Lieler"),
            array("id" => 580, "stop_org" => "Lilien", "stop" => "Lilien"),
            array("id" => 581, "stop_org" => "Limpach", "stop" => "Limpach"),
            array("id" => 582, "stop_org" => "Limpertsberg (Luxembourg)", "stop" => "Limpertsberg (Luxembourg)"),
            array("id" => 583, "stop_org" => "Linger", "stop" => "Linger"),
            array("id" => 584, "stop_org" => "Lintgen", "stop" => "Lintgen"),
            array("id" => 585, "stop_org" => "Lipperscheid", "stop" => "Lipperscheid"),
            array("id" => 586, "stop_org" => "Lipperscheid-Dellt", "stop" => "Lipperscheid-Dellt"),
            array("id" => 587, "stop_org" => "Livange", "stop" => "Livange"),
            array("id" => 588, "stop_org" => "Longsdorf", "stop" => "Longsdorf"),
            array("id" => 589, "stop_org" => "Lorentzscheuer (Ferme de)", "stop" => "Lorentzscheuer (Ferme de)"),
            array("id" => 590, "stop_org" => "Lorentzweiler", "stop" => "Lorentzweiler"),
            array("id" => 591, "stop_org" => "Lullange", "stop" => "Lullange"),
            array("id" => 592, "stop_org" => "Lultzhausen", "stop" => "Lultzhausen"),
            array("id" => 593, "stop_org" => "Luxembourg", "stop" => "Luxembourg"),
            array("id" => 594, "stop_org" => "Luxembourg-Gare", "stop" => "Luxembourg-Gare"),
            array("id" => 595, "stop_org" => "Léerhaff", "stop" => "Léerhaff"),
            array("id" => 596, "stop_org" => "Léresmillen", "stop" => "Léresmillen"),
            array("id" => 597, "stop_org" => "Lévelange", "stop" => "Lévelange"),
            array("id" => 598, "stop_org" => "Lëpschterhaff", "stop" => "Lëpschterhaff"),
            array("id" => 599, "stop_org" => "Löftgermillen", "stop" => "Löftgermillen"),
            array("id" => 600, "stop_org" => "Maarkebaach", "stop" => "Maarkebaach"),
            array("id" => 601, "stop_org" => "Machtum", "stop" => "Machtum"),
            array("id" => 602, "stop_org" => "Mamer", "stop" => "Mamer"),
            array("id" => 603, "stop_org" => "Manertchen", "stop" => "Manertchen"),
            array("id" => 604, "stop_org" => "Manternach", "stop" => "Manternach"),
            array("id" => 605, "stop_org" => "Mariendallerhaff/Märjendallerhaff", "stop" => "Mariendallerhaff/Märjendallerhaff"),
            array("id" => 606, "stop_org" => "Marienthal", "stop" => "Marienthal"),
            array("id" => 607, "stop_org" => "Marnach", "stop" => "Marnach"),
            array("id" => 608, "stop_org" => "Marscherwald", "stop" => "Marscherwald"),
            array("id" => 609, "stop_org" => "Martelinville", "stop" => "Martelinville"),
            array("id" => 610, "stop_org" => "Marxberg", "stop" => "Marxberg"),
            array("id" => 611, "stop_org" => "Marxeknupp", "stop" => "Marxeknupp"),
            array("id" => 612, "stop_org" => "Marxmillen", "stop" => "Marxmillen"),
            array("id" => 613, "stop_org" => "Masseler", "stop" => "Masseler"),
            array("id" => 614, "stop_org" => "Matgeshaff", "stop" => "Matgeshaff"),
            array("id" => 615, "stop_org" => "Maulusmuehle", "stop" => "Maulusmuehle"),
            array("id" => 616, "stop_org" => "Maulusmühle", "stop" => "Maulusmühle"),
            array("id" => 617, "stop_org" => "Mecher (Clervaux)", "stop" => "Mecher (Clervaux)"),
            array("id" => 618, "stop_org" => "Mecher (Haute-Sûre)", "stop" => "Mecher (Haute-Sûre)"),
            array("id" => 619, "stop_org" => "Mecher (Kaundorf)", "stop" => "Mecher (Kaundorf)"),
            array("id" => 620, "stop_org" => "Medernach", "stop" => "Medernach"),
            array("id" => 621, "stop_org" => "Medingen", "stop" => "Medingen"),
            array("id" => 622, "stop_org" => "Meispelt", "stop" => "Meispelt"),
            array("id" => 623, "stop_org" => "Mensdorf", "stop" => "Mensdorf"),
            array("id" => 624, "stop_org" => "Merkholtz", "stop" => "Merkholtz"),
            array("id" => 625, "stop_org" => "Merl (Luxembourg)", "stop" => "Merl (Luxembourg)"),
            array("id" => 626, "stop_org" => "Mersch", "stop" => "Mersch"),
            array("id" => 627, "stop_org" => "Merscheid (Eschdorf)", "stop" => "Merscheid (Eschdorf)"),
            array("id" => 628, "stop_org" => "Merscheid (Putscheid)", "stop" => "Merscheid (Putscheid)"),
            array("id" => 629, "stop_org" => "Mertert", "stop" => "Mertert"),
            array("id" => 630, "stop_org" => "Mertzig", "stop" => "Mertzig"),
            array("id" => 631, "stop_org" => "Meysembourg", "stop" => "Meysembourg"),
            array("id" => 632, "stop_org" => "Michelau", "stop" => "Michelau"),
            array("id" => 633, "stop_org" => "Michelbouch", "stop" => "Michelbouch"),
            array("id" => 634, "stop_org" => "Michelsbierg", "stop" => "Michelsbierg"),
            array("id" => 635, "stop_org" => "Michelshaff / Méchelshaff", "stop" => "Michelshaff / Méchelshaff"),
            array("id" => 636, "stop_org" => "Misère-Ferme", "stop" => "Misère-Ferme"),
            array("id" => 637, "stop_org" => "Moersdorf", "stop" => "Moersdorf"),
            array("id" => 638, "stop_org" => "Moesdorf", "stop" => "Moesdorf"),
            array("id" => 639, "stop_org" => "Moestroff", "stop" => "Moestroff"),
            array("id" => 640, "stop_org" => "Mompach", "stop" => "Mompach"),
            array("id" => 641, "stop_org" => "Mondercange", "stop" => "Mondercange"),
            array("id" => 642, "stop_org" => "Mondorf-Route", "stop" => "Mondorf-Route"),
            array("id" => 643, "stop_org" => "Mondorf-les-Bains", "stop" => "Mondorf-les-Bains"),
            array("id" => 644, "stop_org" => "Mont St. Nicolas", "stop" => "Mont St. Nicolas"),
            array("id" => 645, "stop_org" => "Moserhaff", "stop" => "Moserhaff"),
            array("id" => 646, "stop_org" => "Mouschbierg", "stop" => "Mouschbierg"),
            array("id" => 647, "stop_org" => "Moutfort", "stop" => "Moutfort"),
            array("id" => 648, "stop_org" => "Mullendorf", "stop" => "Mullendorf"),
            array("id" => 649, "stop_org" => "Mullerthal", "stop" => "Mullerthal"),
            array("id" => 650, "stop_org" => "Munsbach", "stop" => "Munsbach"),
            array("id" => 651, "stop_org" => "Munsbach - Château", "stop" => "Munsbach - Château"),
            array("id" => 652, "stop_org" => "Munshausen", "stop" => "Munshausen"),
            array("id" => 653, "stop_org" => "Mélickshaff", "stop" => "Mélickshaff"),
            array("id" => 654, "stop_org" => "Mëtschenhaff", "stop" => "Mëtschenhaff"),
            array("id" => 655, "stop_org" => "Mühlbach", "stop" => "Mühlbach"),
            array("id" => 656, "stop_org" => "Mühlenbach (Luxembourg)", "stop" => "Mühlenbach (Luxembourg)"),
            array("id" => 657, "stop_org" => "Münschecker", "stop" => "Münschecker"),
            array("id" => 658, "stop_org" => "Nachtmanderscheid", "stop" => "Nachtmanderscheid"),
            array("id" => 659, "stop_org" => "Nagem", "stop" => "Nagem"),
            array("id" => 660, "stop_org" => "Nagem (Ferme de)", "stop" => "Nagem (Ferme de)"),
            array("id" => 661, "stop_org" => "Nagemerberg", "stop" => "Nagemerberg"),
            array("id" => 662, "stop_org" => "Neidhausen", "stop" => "Neidhausen"),
            array("id" => 663, "stop_org" => "Neienshaff", "stop" => "Neienshaff"),
            array("id" => 664, "stop_org" => "Neihaff (Insenborn)", "stop" => "Neihaff (Insenborn)"),
            array("id" => 665, "stop_org" => "Neihaff (Ingeldorf)", "stop" => "Neihaff (Ingeldorf)"),
            array("id" => 666, "stop_org" => "Neiluerenzscheierhaff", "stop" => "Neiluerenzscheierhaff"),
            array("id" => 667, "stop_org" => "Neimillen (Echternach)", "stop" => "Neimillen (Echternach)"),
            array("id" => 668, "stop_org" => "Neimillen (Ermsdorf)", "stop" => "Neimillen (Ermsdorf)"),
            array("id" => 669, "stop_org" => "Neimillen (Grosbous)", "stop" => "Neimillen (Grosbous)"),
            array("id" => 670, "stop_org" => "Neimillen (Hoffelt)", "stop" => "Neimillen (Hoffelt)"),
            array("id" => 671, "stop_org" => "Neimillen (Koerich)", "stop" => "Neimillen (Koerich)"),
            array("id" => 672, "stop_org" => "Neimillen (Mamer)", "stop" => "Neimillen (Mamer)"),
            array("id" => 673, "stop_org" => "Neimillen (Schifflange)", "stop" => "Neimillen (Schifflange)"),
            array("id" => 674, "stop_org" => "Neirodeschhaff", "stop" => "Neirodeschhaff"),
            array("id" => 675, "stop_org" => "Neudorf", "stop" => "Neudorf"),
            array("id" => 676, "stop_org" => "Neuhaeusgen", "stop" => "Neuhaeusgen"),
            array("id" => 677, "stop_org" => "Neunhausen", "stop" => "Neunhausen"),
            array("id" => 678, "stop_org" => "Niederanven", "stop" => "Niederanven"),
            array("id" => 679, "stop_org" => "Niederdonven", "stop" => "Niederdonven"),
            array("id" => 680, "stop_org" => "Niederfeulen", "stop" => "Niederfeulen"),
            array("id" => 681, "stop_org" => "Niederglabach", "stop" => "Niederglabach"),
            array("id" => 682, "stop_org" => "Niederkorn", "stop" => "Niederkorn"),
            array("id" => 683, "stop_org" => "Niederpallen", "stop" => "Niederpallen"),
            array("id" => 684, "stop_org" => "Niederpallen-Moulin", "stop" => "Niederpallen-Moulin"),
            array("id" => 685, "stop_org" => "Niedert (Ferme de)", "stop" => "Niedert (Ferme de)"),
            array("id" => 686, "stop_org" => "Niederwampach", "stop" => "Niederwampach"),
            array("id" => 687, "stop_org" => "Niederwampach-Halte", "stop" => "Niederwampach-Halte"),
            array("id" => 688, "stop_org" => "Niederwiltz", "stop" => "Niederwiltz"),
            array("id" => 689, "stop_org" => "Niesenthal", "stop" => "Niesenthal"),
            array("id" => 690, "stop_org" => "Nocher", "stop" => "Nocher"),
            array("id" => 691, "stop_org" => "Nocher-Route", "stop" => "Nocher-Route"),
            array("id" => 692, "stop_org" => "Noerdange", "stop" => "Noerdange"),
            array("id" => 693, "stop_org" => "Noertrange", "stop" => "Noertrange"),
            array("id" => 694, "stop_org" => "Noertzange", "stop" => "Noertzange"),
            array("id" => 695, "stop_org" => "Nommern", "stop" => "Nommern"),
            array("id" => 696, "stop_org" => "Nospelt", "stop" => "Nospelt"),
            array("id" => 697, "stop_org" => "Nothum", "stop" => "Nothum"),
            array("id" => 698, "stop_org" => "Oberanven", "stop" => "Oberanven"),
            array("id" => 699, "stop_org" => "Oberdonven", "stop" => "Oberdonven"),
            array("id" => 700, "stop_org" => "Obereisenbach", "stop" => "Obereisenbach"),
            array("id" => 701, "stop_org" => "Oberfeulen", "stop" => "Oberfeulen"),
            array("id" => 702, "stop_org" => "Oberglabach", "stop" => "Oberglabach"),
            array("id" => 703, "stop_org" => "Oberkorn", "stop" => "Oberkorn"),
            array("id" => 704, "stop_org" => "Oberpallen", "stop" => "Oberpallen"),
            array("id" => 705, "stop_org" => "Oberschlinder", "stop" => "Oberschlinder"),
            array("id" => 706, "stop_org" => "Oberwampach", "stop" => "Oberwampach"),
            array("id" => 707, "stop_org" => "Oenneschtmillen", "stop" => "Oenneschtmillen"),
            array("id" => 708, "stop_org" => "Oetrange", "stop" => "Oetrange"),
            array("id" => 709, "stop_org" => "Oetrange-Moulin", "stop" => "Oetrange-Moulin"),
            array("id" => 710, "stop_org" => "Oligsmühle (Christnach)", "stop" => "Oligsmühle (Christnach)"),
            array("id" => 711, "stop_org" => "Oligsmühle (Medernach)", "stop" => "Oligsmühle (Medernach)"),
            array("id" => 712, "stop_org" => "Olingen", "stop" => "Olingen"),
            array("id" => 713, "stop_org" => "Olm", "stop" => "Olm"),
            array("id" => 714, "stop_org" => "Openthalt", "stop" => "Openthalt"),
            array("id" => 715, "stop_org" => "Ospern", "stop" => "Ospern"),
            array("id" => 716, "stop_org" => "Osterbour (Larochette)", "stop" => "Osterbour (Larochette)"),
            array("id" => 717, "stop_org" => "Osterbour (Nagem)", "stop" => "Osterbour (Nagem)"),
            array("id" => 718, "stop_org" => "Osterholz", "stop" => "Osterholz"),
            array("id" => 719, "stop_org" => "Osweiler", "stop" => "Osweiler"),
            array("id" => 720, "stop_org" => "PREIZERDAUL (Commune de)", "stop" => "PREIZERDAUL (Commune de)"),
            array("id" => 721, "stop_org" => "Pafebruch", "stop" => "Pafebruch"),
            array("id" => 722, "stop_org" => "Peckelshaff", "stop" => "Peckelshaff"),
            array("id" => 723, "stop_org" => "Peppange", "stop" => "Peppange"),
            array("id" => 724, "stop_org" => "Perlé", "stop" => "Perlé"),
            array("id" => 725, "stop_org" => "Petit-Nobressart", "stop" => "Petit-Nobressart"),
            array("id" => 726, "stop_org" => "Pettingen", "stop" => "Pettingen"),
            array("id" => 727, "stop_org" => "Pfaffenberg", "stop" => "Pfaffenberg"),
            array("id" => 728, "stop_org" => "Pfaffenthal (Luxembourg)", "stop" => "Pfaffenthal (Luxembourg)"),
            array("id" => 729, "stop_org" => "Pintsch", "stop" => "Pintsch"),
            array("id" => 730, "stop_org" => "Pissange", "stop" => "Pissange"),
            array("id" => 731, "stop_org" => "Plankenhaff", "stop" => "Plankenhaff"),
            array("id" => 732, "stop_org" => "Platen", "stop" => "Platen"),
            array("id" => 733, "stop_org" => "Pleitrange", "stop" => "Pleitrange"),
            array("id" => 734, "stop_org" => "Pletschette", "stop" => "Pletschette"),
            array("id" => 735, "stop_org" => "Pommerloch", "stop" => "Pommerloch"),
            array("id" => 736, "stop_org" => "Pontpierre", "stop" => "Pontpierre"),
            array("id" => 737, "stop_org" => "Poschend", "stop" => "Poschend"),
            array("id" => 738, "stop_org" => "Posselt", "stop" => "Posselt"),
            array("id" => 739, "stop_org" => "Potaschberg", "stop" => "Potaschberg"),
            array("id" => 740, "stop_org" => "Pratz", "stop" => "Pratz"),
            array("id" => 741, "stop_org" => "Prettingen", "stop" => "Prettingen"),
            array("id" => 742, "stop_org" => "Prétemerhaff", "stop" => "Prétemerhaff"),
            array("id" => 743, "stop_org" => "Pull", "stop" => "Pull"),
            array("id" => 744, "stop_org" => "Pulvermühl (Luxembourg)", "stop" => "Pulvermühl (Luxembourg)"),
            array("id" => 745, "stop_org" => "Putscheid", "stop" => "Putscheid"),
            array("id" => 746, "stop_org" => "Pétange", "stop" => "Pétange"),
            array("id" => 747, "stop_org" => "Quatre-Vents (Eschdorf)", "stop" => "Quatre-Vents (Eschdorf)"),
            array("id" => 748, "stop_org" => "Quatre-Vents (Kehlen)", "stop" => "Quatre-Vents (Kehlen)"),
            array("id" => 749, "stop_org" => "Rambrouch", "stop" => "Rambrouch"),
            array("id" => 750, "stop_org" => "Rameldange", "stop" => "Rameldange"),
            array("id" => 751, "stop_org" => "Rashaff", "stop" => "Rashaff"),
            array("id" => 752, "stop_org" => "Reckange", "stop" => "Reckange"),
            array("id" => 753, "stop_org" => "Reckange-Barrière", "stop" => "Reckange-Barrière"),
            array("id" => 754, "stop_org" => "Reckange-sur-Mess", "stop" => "Reckange-sur-Mess"),
            array("id" => 755, "stop_org" => "Reckenthal", "stop" => "Reckenthal"),
            array("id" => 756, "stop_org" => "Reckingerhof", "stop" => "Reckingerhof"),
            array("id" => 757, "stop_org" => "Redange/Attert", "stop" => "Redange/Attert"),
            array("id" => 758, "stop_org" => "Redingshaff", "stop" => "Redingshaff"),
            array("id" => 759, "stop_org" => "Reichlange", "stop" => "Reichlange"),
            array("id" => 760, "stop_org" => "Reifeschbierg", "stop" => "Reifeschbierg"),
            array("id" => 761, "stop_org" => "Reimberg", "stop" => "Reimberg"),
            array("id" => 762, "stop_org" => "Reineschhaff", "stop" => "Reineschhaff"),
            array("id" => 763, "stop_org" => "Reisdorf", "stop" => "Reisdorf"),
            array("id" => 764, "stop_org" => "Reisermillen", "stop" => "Reisermillen"),
            array("id" => 765, "stop_org" => "Remerschen", "stop" => "Remerschen"),
            array("id" => 766, "stop_org" => "Remich", "stop" => "Remich"),
            array("id" => 767, "stop_org" => "Reuland", "stop" => "Reuland"),
            array("id" => 768, "stop_org" => "Reuland-Moulin", "stop" => "Reuland-Moulin"),
            array("id" => 769, "stop_org" => "Reuler", "stop" => "Reuler"),
            array("id" => 770, "stop_org" => "Riesenhof", "stop" => "Riesenhof"),
            array("id" => 771, "stop_org" => "Rindschleiden", "stop" => "Rindschleiden"),
            array("id" => 772, "stop_org" => "Ringbaach", "stop" => "Ringbaach"),
            array("id" => 773, "stop_org" => "Ringel", "stop" => "Ringel"),
            array("id" => 774, "stop_org" => "Ringel (Ferme de)", "stop" => "Ringel (Ferme de)"),
            array("id" => 775, "stop_org" => "Rippig", "stop" => "Rippig"),
            array("id" => 776, "stop_org" => "Rippweiler", "stop" => "Rippweiler"),
            array("id" => 777, "stop_org" => "Rodange", "stop" => "Rodange"),
            array("id" => 778, "stop_org" => "Rodenbourg", "stop" => "Rodenbourg"),
            array("id" => 779, "stop_org" => "Roder", "stop" => "Roder"),
            array("id" => 780, "stop_org" => "Rodershausen", "stop" => "Rodershausen"),
            array("id" => 781, "stop_org" => "Roedgen", "stop" => "Roedgen"),
            array("id" => 782, "stop_org" => "Roedt", "stop" => "Roedt"),
            array("id" => 783, "stop_org" => "Roeser", "stop" => "Roeser"),
            array("id" => 784, "stop_org" => "Rolling", "stop" => "Rolling"),
            array("id" => 785, "stop_org" => "Rollingen", "stop" => "Rollingen"),
            array("id" => 786, "stop_org" => "Rollingergrund (Luxembourg)", "stop" => "Rollingergrund (Luxembourg)"),
            array("id" => 787, "stop_org" => "Rombach-Martelange", "stop" => "Rombach-Martelange"),
            array("id" => 788, "stop_org" => "Ronnebësch", "stop" => "Ronnebësch"),
            array("id" => 789, "stop_org" => "Roodt (Ell)", "stop" => "Roodt (Ell)"),
            array("id" => 790, "stop_org" => "Roodt (Septfontaines)", "stop" => "Roodt (Septfontaines)"),
            array("id" => 791, "stop_org" => "Roodt-sur-Syre", "stop" => "Roodt-sur-Syre"),
            array("id" => 792, "stop_org" => "Roost (Bissen)", "stop" => "Roost (Bissen)"),
            array("id" => 793, "stop_org" => "Rosport", "stop" => "Rosport"),
            array("id" => 794, "stop_org" => "Rossmühle", "stop" => "Rossmühle"),
            array("id" => 795, "stop_org" => "Rosswinkelerhaff", "stop" => "Rosswinkelerhaff"),
            array("id" => 796, "stop_org" => "Roudbaach", "stop" => "Roudbaach"),
            array("id" => 797, "stop_org" => "Roudenhaff (Bridel)", "stop" => "Roudenhaff (Bridel)"),
            array("id" => 798, "stop_org" => "Roudenhaff (Echternach)", "stop" => "Roudenhaff (Echternach)"),
            array("id" => 799, "stop_org" => "Roullingen", "stop" => "Roullingen"),
            array("id" => 800, "stop_org" => "Rouschthaff", "stop" => "Rouschthaff"),
            array("id" => 801, "stop_org" => "Rumelange", "stop" => "Rumelange"),
            array("id" => 802, "stop_org" => "Rumlange", "stop" => "Rumlange"),
            array("id" => 803, "stop_org" => "Saeul", "stop" => "Saeul"),
            array("id" => 804, "stop_org" => "Sandweiler", "stop" => "Sandweiler"),
            array("id" => 805, "stop_org" => "Sandweiler-Contern Gare", "stop" => "Sandweiler-Contern Gare"),
            array("id" => 806, "stop_org" => "Sanem", "stop" => "Sanem"),
            array("id" => 807, "stop_org" => "Sassel", "stop" => "Sassel"),
            array("id" => 808, "stop_org" => "Savelborn", "stop" => "Savelborn"),
            array("id" => 809, "stop_org" => "Schack", "stop" => "Schack"),
            array("id" => 810, "stop_org" => "Schandel", "stop" => "Schandel"),
            array("id" => 811, "stop_org" => "Scheedbierg", "stop" => "Scheedbierg"),
            array("id" => 812, "stop_org" => "Scheedhaff", "stop" => "Scheedhaff"),
            array("id" => 813, "stop_org" => "Scheedheck", "stop" => "Scheedheck"),
            array("id" => 814, "stop_org" => "Scheidel", "stop" => "Scheidel"),
            array("id" => 815, "stop_org" => "Scheidgen", "stop" => "Scheidgen"),
            array("id" => 816, "stop_org" => "Scheierhaff (Belvaux)", "stop" => "Scheierhaff (Belvaux)"),
            array("id" => 817, "stop_org" => "Scheierhaff (Canach)", "stop" => "Scheierhaff (Canach)"),
            array("id" => 818, "stop_org" => "Scheierhaff (Moesdorf)", "stop" => "Scheierhaff (Moesdorf)"),
            array("id" => 819, "stop_org" => "Scheierhaff (Vianden)", "stop" => "Scheierhaff (Vianden)"),
            array("id" => 820, "stop_org" => "Schengen", "stop" => "Schengen"),
            array("id" => 821, "stop_org" => "Scherbach", "stop" => "Scherbach"),
            array("id" => 822, "stop_org" => "Scherfenhaff", "stop" => "Scherfenhaff"),
            array("id" => 823, "stop_org" => "Scheuerberg", "stop" => "Scheuerberg"),
            array("id" => 824, "stop_org" => "Schieren", "stop" => "Schieren"),
            array("id" => 825, "stop_org" => "Schieren (Ferme de)", "stop" => "Schieren (Ferme de)"),
            array("id" => 826, "stop_org" => "Schieren-Moulin", "stop" => "Schieren-Moulin"),
            array("id" => 827, "stop_org" => "Schifflange", "stop" => "Schifflange"),
            array("id" => 828, "stop_org" => "Schiltzberg", "stop" => "Schiltzberg"),
            array("id" => 829, "stop_org" => "Schimpach", "stop" => "Schimpach"),
            array("id" => 830, "stop_org" => "Schlammesté / Schlammestee", "stop" => "Schlammesté / Schlammestee"),
            array("id" => 831, "stop_org" => "Schleederhaff", "stop" => "Schleederhaff"),
            array("id" => 832, "stop_org" => "Schleif", "stop" => "Schleif"),
            array("id" => 833, "stop_org" => "Schleifmillen (Altlinster)", "stop" => "Schleifmillen (Altlinster)"),
            array("id" => 834, "stop_org" => "Schleifmühle (Luxembourg)", "stop" => "Schleifmühle (Luxembourg)"),
            array("id" => 835, "stop_org" => "Schleiterhaff", "stop" => "Schleiterhaff"),
            array("id" => 836, "stop_org" => "Schlindermanderscheid", "stop" => "Schlindermanderscheid"),
            array("id" => 837, "stop_org" => "Schléiwenhaff", "stop" => "Schléiwenhaff"),
            array("id" => 838, "stop_org" => "Schmuelen", "stop" => "Schmuelen"),
            array("id" => 839, "stop_org" => "Schmëttewier", "stop" => "Schmëttewier"),
            array("id" => 840, "stop_org" => "Schockmillen", "stop" => "Schockmillen"),
            array("id" => 841, "stop_org" => "Schoenfels", "stop" => "Schoenfels"),
            array("id" => 842, "stop_org" => "Schoenfels-Moulin", "stop" => "Schoenfels-Moulin"),
            array("id" => 843, "stop_org" => "Schoos", "stop" => "Schoos"),
            array("id" => 844, "stop_org" => "Schorenshaff", "stop" => "Schorenshaff"),
            array("id" => 845, "stop_org" => "Schouweiler", "stop" => "Schouweiler"),
            array("id" => 846, "stop_org" => "Schrassig", "stop" => "Schrassig"),
            array("id" => 847, "stop_org" => "Schrassig-Kuelebierg", "stop" => "Schrassig-Kuelebierg"),
            array("id" => 848, "stop_org" => "Schroedeschhaff", "stop" => "Schroedeschhaff"),
            array("id" => 849, "stop_org" => "Schrondweiler", "stop" => "Schrondweiler"),
            array("id" => 850, "stop_org" => "Schumannseck", "stop" => "Schumannseck"),
            array("id" => 851, "stop_org" => "Schummeschmillen", "stop" => "Schummeschmillen"),
            array("id" => 852, "stop_org" => "Schuttrange", "stop" => "Schuttrange"),
            array("id" => 853, "stop_org" => "Schwaarzenhaff", "stop" => "Schwaarzenhaff"),
            array("id" => 854, "stop_org" => "Schwanenthal", "stop" => "Schwanenthal"),
            array("id" => 855, "stop_org" => "Schwanterhaff", "stop" => "Schwanterhaff"),
            array("id" => 856, "stop_org" => "Schwebach", "stop" => "Schwebach"),
            array("id" => 857, "stop_org" => "Schwebsingen", "stop" => "Schwebsingen"),
            array("id" => 858, "stop_org" => "Schweich", "stop" => "Schweich"),
            array("id" => 859, "stop_org" => "Schwiedelbrouch", "stop" => "Schwiedelbrouch"),
            array("id" => 860, "stop_org" => "Schwébecherbréck", "stop" => "Schwébecherbréck"),
            array("id" => 861, "stop_org" => "Schäferrieder", "stop" => "Schäferrieder"),
            array("id" => 862, "stop_org" => "Schéiferei", "stop" => "Schéiferei"),
            array("id" => 863, "stop_org" => "Schüttburg-Château", "stop" => "Schüttburg-Château"),
            array("id" => 864, "stop_org" => "Schüttburg-Moulin", "stop" => "Schüttburg-Moulin"),
            array("id" => 865, "stop_org" => "Seitert", "stop" => "Seitert"),
            array("id" => 866, "stop_org" => "Selscheid", "stop" => "Selscheid"),
            array("id" => 867, "stop_org" => "Seltz", "stop" => "Seltz"),
            array("id" => 868, "stop_org" => "Senningen", "stop" => "Senningen"),
            array("id" => 869, "stop_org" => "Senningerberg", "stop" => "Senningerberg"),
            array("id" => 870, "stop_org" => "Septfontaines", "stop" => "Septfontaines"),
            array("id" => 871, "stop_org" => "Septfontaines (Luxembourg)", "stop" => "Septfontaines (Luxembourg)"),
            array("id" => 872, "stop_org" => "Seylerhaff", "stop" => "Seylerhaff"),
            array("id" => 873, "stop_org" => "Siebenaler", "stop" => "Siebenaler"),
            array("id" => 874, "stop_org" => "Simmerfarm", "stop" => "Simmerfarm"),
            array("id" => 875, "stop_org" => "Simmerschmelz", "stop" => "Simmerschmelz"),
            array("id" => 876, "stop_org" => "Siwemuergen", "stop" => "Siwemuergen"),
            array("id" => 877, "stop_org" => "Sliepenhaff", "stop" => "Sliepenhaff"),
            array("id" => 878, "stop_org" => "Soleuvre", "stop" => "Soleuvre"),
            array("id" => 879, "stop_org" => "Sonlez", "stop" => "Sonlez"),
            array("id" => 880, "stop_org" => "Soup (Heffingen)", "stop" => "Soup (Heffingen)"),
            array("id" => 881, "stop_org" => "Soup (Reisdorf)", "stop" => "Soup (Reisdorf)"),
            array("id" => 882, "stop_org" => "Specksmillen", "stop" => "Specksmillen"),
            array("id" => 883, "stop_org" => "Sprinkange", "stop" => "Sprinkange"),
            array("id" => 884, "stop_org" => "Stadtbredimus", "stop" => "Stadtbredimus"),
            array("id" => 885, "stop_org" => "Stafelter (Staffelstein)", "stop" => "Stafelter (Staffelstein)"),
            array("id" => 886, "stop_org" => "Stegen", "stop" => "Stegen"),
            array("id" => 887, "stop_org" => "Steinfort", "stop" => "Steinfort"),
            array("id" => 888, "stop_org" => "Steinheim", "stop" => "Steinheim"),
            array("id" => 889, "stop_org" => "Steinsel", "stop" => "Steinsel"),
            array("id" => 890, "stop_org" => "Stockem", "stop" => "Stockem"),
            array("id" => 891, "stop_org" => "Stolzembourg", "stop" => "Stolzembourg"),
            array("id" => 892, "stop_org" => "Stoppelhaff", "stop" => "Stoppelhaff"),
            array("id" => 893, "stop_org" => "Strassen", "stop" => "Strassen"),
            array("id" => 894, "stop_org" => "Stuppicht", "stop" => "Stuppicht"),
            array("id" => 895, "stop_org" => "Surré", "stop" => "Surré"),
            array("id" => 896, "stop_org" => "Syrdall", "stop" => "Syrdall"),
            array("id" => 897, "stop_org" => "Syrdallschlass", "stop" => "Syrdallschlass"),
            array("id" => 898, "stop_org" => "Syren", "stop" => "Syren"),
            array("id" => 899, "stop_org" => "Tadler", "stop" => "Tadler"),
            array("id" => 900, "stop_org" => "Tadler-Moulin", "stop" => "Tadler-Moulin"),
            array("id" => 901, "stop_org" => "Tandel", "stop" => "Tandel"),
            array("id" => 902, "stop_org" => "Tarchamps", "stop" => "Tarchamps"),
            array("id" => 903, "stop_org" => "Theinshaff", "stop" => "Theinshaff"),
            array("id" => 904, "stop_org" => "Thillsmillen", "stop" => "Thillsmillen"),
            array("id" => 905, "stop_org" => "Tintesmühle", "stop" => "Tintesmühle"),
            array("id" => 906, "stop_org" => "Tomm (Bastendorf)", "stop" => "Tomm (Bastendorf)"),
            array("id" => 907, "stop_org" => "Tomm (Fouhren)", "stop" => "Tomm (Fouhren)"),
            array("id" => 908, "stop_org" => "Tossebierg", "stop" => "Tossebierg"),
            array("id" => 909, "stop_org" => "Toussaintsmillen", "stop" => "Toussaintsmillen"),
            array("id" => 910, "stop_org" => "Trintange", "stop" => "Trintange"),
            array("id" => 911, "stop_org" => "Troine", "stop" => "Troine"),
            array("id" => 912, "stop_org" => "Troine-Route", "stop" => "Troine-Route"),
            array("id" => 913, "stop_org" => "Troisvierges", "stop" => "Troisvierges"),
            array("id" => 914, "stop_org" => "Trudlermillen", "stop" => "Trudlermillen"),
            array("id" => 915, "stop_org" => "Tschiddeschmillen", "stop" => "Tschiddeschmillen"),
            array("id" => 916, "stop_org" => "Tuntange", "stop" => "Tuntange"),
            array("id" => 917, "stop_org" => "Turelbaach", "stop" => "Turelbaach"),
            array("id" => 918, "stop_org" => "Tutschemillen", "stop" => "Tutschemillen"),
            array("id" => 919, "stop_org" => "Tétange", "stop" => "Tétange"),
            array("id" => 920, "stop_org" => "Uebersyren", "stop" => "Uebersyren"),
            array("id" => 921, "stop_org" => "Untereisenbach", "stop" => "Untereisenbach"),
            array("id" => 922, "stop_org" => "Unterschlinder", "stop" => "Unterschlinder"),
            array("id" => 923, "stop_org" => "Urspelt", "stop" => "Urspelt"),
            array("id" => 924, "stop_org" => "Useldange", "stop" => "Useldange"),
            array("id" => 925, "stop_org" => "VIANDEN-Château", "stop" => "VIANDEN-Château"),
            array("id" => 926, "stop_org" => "Verlorenkost (Luxembourg)", "stop" => "Verlorenkost (Luxembourg)"),
            array("id" => 927, "stop_org" => "Vesquenhaff", "stop" => "Vesquenhaff"),
            array("id" => 928, "stop_org" => "Vianden", "stop" => "Vianden"),
            array("id" => 929, "stop_org" => "Vichten", "stop" => "Vichten"),
            array("id" => 930, "stop_org" => "WILTZ-Château", "stop" => "WILTZ-Château"),
            array("id" => 931, "stop_org" => "Wahl", "stop" => "Wahl"),
            array("id" => 932, "stop_org" => "Wahlhausen", "stop" => "Wahlhausen"),
            array("id" => 933, "stop_org" => "Wahlhausen Dickt", "stop" => "Wahlhausen Dickt"),
            array("id" => 934, "stop_org" => "Waldbierg", "stop" => "Waldbierg"),
            array("id" => 935, "stop_org" => "Waldbillig", "stop" => "Waldbillig"),
            array("id" => 936, "stop_org" => "Waldbredimus", "stop" => "Waldbredimus"),
            array("id" => 937, "stop_org" => "Waldhof", "stop" => "Waldhof"),
            array("id" => 938, "stop_org" => "Walferdange", "stop" => "Walferdange"),
            array("id" => 939, "stop_org" => "Wallendorf-Pont", "stop" => "Wallendorf-Pont"),
            array("id" => 940, "stop_org" => "Walsdorf", "stop" => "Walsdorf"),
            array("id" => 941, "stop_org" => "Warken", "stop" => "Warken"),
            array("id" => 942, "stop_org" => "Wasserbillig", "stop" => "Wasserbillig"),
            array("id" => 943, "stop_org" => "Watrange", "stop" => "Watrange"),
            array("id" => 944, "stop_org" => "Watschenterhaff", "stop" => "Watschenterhaff"),
            array("id" => 945, "stop_org" => "Wealerhaff", "stop" => "Wealerhaff"),
            array("id" => 946, "stop_org" => "Webeschhaff", "stop" => "Webeschhaff"),
            array("id" => 947, "stop_org" => "Wecker", "stop" => "Wecker"),
            array("id" => 948, "stop_org" => "Wecker-Gare", "stop" => "Wecker-Gare"),
            array("id" => 949, "stop_org" => "Weicherdange", "stop" => "Weicherdange"),
            array("id" => 950, "stop_org" => "Weidemillen", "stop" => "Weidemillen"),
            array("id" => 951, "stop_org" => "Weidendall / Val des Oseraies", "stop" => "Weidendall / Val des Oseraies"),
            array("id" => 952, "stop_org" => "Weidingen", "stop" => "Weidingen"),
            array("id" => 953, "stop_org" => "Weiler (Hachiville)", "stop" => "Weiler (Hachiville)"),
            array("id" => 954, "stop_org" => "Weiler (Putscheid)", "stop" => "Weiler (Putscheid)"),
            array("id" => 955, "stop_org" => "Weiler-la-Tour", "stop" => "Weiler-la-Tour"),
            array("id" => 956, "stop_org" => "Weilerbach", "stop" => "Weilerbach"),
            array("id" => 957, "stop_org" => "Weimershof (Luxembourg)", "stop" => "Weimershof (Luxembourg)"),
            array("id" => 958, "stop_org" => "Weimerskirch (Luxembourg)", "stop" => "Weimerskirch (Luxembourg)"),
            array("id" => 959, "stop_org" => "Weissenhaff", "stop" => "Weissenhaff"),
            array("id" => 960, "stop_org" => "Weiswampach", "stop" => "Weiswampach"),
            array("id" => 961, "stop_org" => "Welfrange", "stop" => "Welfrange"),
            array("id" => 962, "stop_org" => "Wellenstein", "stop" => "Wellenstein"),
            array("id" => 963, "stop_org" => "Welscheid", "stop" => "Welscheid"),
            array("id" => 964, "stop_org" => "Welsdorf", "stop" => "Welsdorf"),
            array("id" => 965, "stop_org" => "Wemperhardt", "stop" => "Wemperhardt"),
            array("id" => 966, "stop_org" => "Weydert (la Ferme)", "stop" => "Weydert (la Ferme)"),
            array("id" => 967, "stop_org" => "Weydig", "stop" => "Weydig"),
            array("id" => 968, "stop_org" => "Weyer", "stop" => "Weyer"),
            array("id" => 969, "stop_org" => "Wickrange", "stop" => "Wickrange"),
            array("id" => 970, "stop_org" => "Wilspull", "stop" => "Wilspull"),
            array("id" => 971, "stop_org" => "Wiltgeshaff", "stop" => "Wiltgeshaff"),
            array("id" => 972, "stop_org" => "Wiltz", "stop" => "Wiltz"),
            array("id" => 973, "stop_org" => "Wilwerdange", "stop" => "Wilwerdange"),
            array("id" => 974, "stop_org" => "Wilwerwiltz", "stop" => "Wilwerwiltz"),
            array("id" => 975, "stop_org" => "Wincrange", "stop" => "Wincrange"),
            array("id" => 976, "stop_org" => "Windhof (Koerich)", "stop" => "Windhof (Koerich)"),
            array("id" => 977, "stop_org" => "Windhof (Welscheid)", "stop" => "Windhof (Welscheid)"),
            array("id" => 978, "stop_org" => "Winseler", "stop" => "Winseler"),
            array("id" => 979, "stop_org" => "Wintrange", "stop" => "Wintrange"),
            array("id" => 980, "stop_org" => "Wollefsmillen", "stop" => "Wollefsmillen"),
            array("id" => 981, "stop_org" => "Wolper", "stop" => "Wolper"),
            array("id" => 982, "stop_org" => "Wolwelange", "stop" => "Wolwelange"),
            array("id" => 983, "stop_org" => "Wormeldange", "stop" => "Wormeldange"),
            array("id" => 984, "stop_org" => "Wormeldange-Haut", "stop" => "Wormeldange-Haut"),
            array("id" => 985, "stop_org" => "Zittig", "stop" => "Zittig")
        );

        DB::table('stop')->insert($locations_lu);

        // php artisan migrate:fresh --seed

    }
}
